export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const AUTH_USER = "AUTH_USER"

export const LOG_OUT = "LOG_OUT";

export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"


export const LOADING_UPLOAD_FILE = "LOADING_UPLOAD_FILE"
export const UPLOAD_FILE = "UPLOAD_FILE"
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR"

export const CREATE_LINK = "CREATE_LINK"
export const CREATE_LINK_ERROR = "CREATE_LINK_ERROR"

export const DISMISS_ALERT = "DISMISS_ALERT"
export const SHOW_ALERT = "SHOW_ALERT"

export const CLEAN_STATE = "CLEAN_STATE"

export const ADD_PASSWORD = "ADD_PASSWORD"
export const ADD_DOWNLOADS = "ADD_DOWNLOADS"
